import { PortfolioItem } from '@/types';

export const portfolioItems: PortfolioItem[] = [
  {
    id: '1',
    title: 'I Built a $100,000 AI Agent in 24 Hours',
    category: 'AI',
    views: '1.8M',
    ctrIncrease: '+28.4% CTR',
    client: 'TechLead Prime',
    description: 'Ultra high-contrast split lighting design with holographic neural node overlays, futuristic neon glow typography, and dramatic expressive subject masking.',
    badge: '1.8M+ Views',
    gradient: 'from-blue-600 via-indigo-900 to-purple-950',
    accentColor: '#3B82F6',
    imageUrl: '/assets/thumbnails/ai.png',
  },
  {
    id: '2',
    title: 'Surviving 100 Days in Hardcore Minecraft Nether',
    category: 'Gaming',
    views: '3.4M',
    ctrIncrease: '+32.1% CTR',
    client: 'PixelKing Gaming',
    description: 'Cinematic lava glow particle composition with volumetric fog effects, high-vibrancy title hierarchy, and dramatic character positioning.',
    badge: '3.4M+ Views',
    gradient: 'from-orange-600 via-red-900 to-amber-950',
    accentColor: '#F97316',
    imageUrl: '/assets/thumbnails/gaming.png',
  },
  {
    id: '3',
    title: 'How Anyone Can Retire at 30 With Index Funds',
    category: 'Finance',
    views: '950K',
    ctrIncrease: '+22.8% CTR',
    client: 'Capital Mastery',
    description: 'Clean luxury finance aesthetic featuring emerald green lighting aura, crisp dollar graphic depth layers, and high-legibility bold typography.',
    badge: '950K+ Views',
    gradient: 'from-emerald-600 via-teal-900 to-slate-950',
    accentColor: '#10B981',
    imageUrl: '/assets/thumbnails/finace.png',
  },
  {
    id: '4',
    title: 'The Dark Secret Behind Quantum Computing',
    category: 'Documentary',
    views: '1.2M',
    ctrIncrease: '+26.5% CTR',
    client: 'Mystery Files',
    description: 'Deep moody cinematic noir color grade with intense spotlight backlighting, mystery symbolism, and high-impact dramatic contrast.',
    badge: '1.2M+ Views',
    gradient: 'from-purple-700 via-slate-900 to-black',
    accentColor: '#8B5CF6',
    imageUrl: '/assets/thumbnails/doucmantery.png',
  },
  {
    id: '5',
    title: 'Apple M4 Ultra Unboxing: RIP Intel?',
    category: 'Tech',
    views: '2.1M',
    ctrIncrease: '+29.0% CTR',
    client: 'Tech Matrix',
    description: 'Futuristic glassmorphic unboxing layout with cyan edge lighting, studio reflections, and bold metallic text rendering.',
    badge: '2.1M+ Views',
    gradient: 'from-cyan-600 via-blue-900 to-slate-950',
    accentColor: '#06B6D4',
    imageUrl: '/assets/thumbnails/tech.png',
  },
  {
    id: '6',
    title: 'How I Learned 5 Languages in 30 Days',
    category: 'Education',
    views: '820K',
    ctrIncrease: '+21.4% CTR',
    client: 'Mindset Academy',
    description: 'High-energy educational layout with dynamic progress bar elements, brain activity neural glow, and compelling facial reaction crop.',
    badge: '820K+ Views',
    gradient: 'from-indigo-600 via-purple-900 to-slate-950',
    accentColor: '#6366F1',
    imageUrl: '/assets/thumbnails/education.png',
  },
  {
    id: '7',
    title: 'Inside Tokyo’s Cyberpunk Underground 2026',
    category: 'Travel',
    views: '1.5M',
    ctrIncrease: '+27.2% CTR',
    client: 'Vagabond World',
    description: 'Neon magenta and teal dual lighting design featuring vibrant Tokyo street signage glow and atmospheric rain reflections.',
    badge: '1.5M+ Views',
    gradient: 'from-pink-600 via-purple-950 to-slate-950',
    accentColor: '#EC4899',
    imageUrl: '/assets/thumbnails/travel.png',
  },
  {
    id: '8',
    title: 'The Ultimate 100M Final Sprint Breakdown',
    category: 'Sports',
    views: '1.1M',
    ctrIncrease: '+24.9% CTR',
    client: 'Apex Athletic',
    description: 'High-action motion blur trailing lines with metallic gold trophy aura, aggressive athletic dynamic tilt, and fiery text highlights.',
    badge: '1.1M+ Views',
    gradient: 'from-yellow-600 via-amber-900 to-slate-950',
    accentColor: '#EAB308',
    imageUrl: '/assets/thumbnails/sports.png',
  },
];
